---
name: JavaScript-Lint
version: 0.01
author:
  - 'Dominic Mitchell <cpan (at) happygiraffe.net>'
abstract: Check JavaScript code for problems
license: bsd
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
requires:
  JavaScript: 0
provides:
  JavaScript::Lint:
    file: lib/JavaScript/Lint.pm
    version: 0.01
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
